# Generated by Django 3.2.13 on 2022-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20220519_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('buy', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
