# Generated by Django 3.2.13 on 2022-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_trades_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(max_length=150)),
                ('trade_price_buy', models.FloatField()),
                ('trade_price_sell', models.FloatField()),
                ('date_modified', models.IntegerField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='commodity',
            field=models.CharField(max_length=150),
        ),
    ]
