# Generated by Django 3.2.13 on 2022-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20220522_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='buy',
        ),
        migrations.AddField(
            model_name='trade',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
