# Generated by Django 3.2.13 on 2022-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20220523_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='session',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
