# Generated by Django 3.2.13 on 2022-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_trade_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=150)),
                ('error_location', models.CharField(max_length=150)),
            ],
        ),
    ]
