# Generated by Django 3.2.13 on 2022-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_errorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
