# Generated by Django 3.2.13 on 2022-05-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_trade_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='cost',
            new_name='profit',
        ),
    ]
