# Generated by Django 3.2.13 on 2022-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_trade_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
