# Generated by Django 3.2.13 on 2022-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_auto_20220523_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
