# Generated by Django 3.2.13 on 2022-05-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buy',
            field=models.BooleanField(default=True),
        ),
    ]
