# Generated by Django 3.2.13 on 2022-05-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_trade_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='units',
            field=models.IntegerField(default=5000),
        ),
    ]
