# Generated by Django 3.2.13 on 2022-05-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_trade_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=0, max_length=150)),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
