# Generated by Django 3.2.13 on 2022-05-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_userprofit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofit',
            old_name='user',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='userprofit',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
