# Generated by Django 3.2.13 on 2022-05-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_auto_20220524_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlist',
            old_name='error_location',
            new_name='session',
        ),
    ]
