# Generated by Django 3.2.13 on 2022-05-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_rename_error_location_errorlist_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlist',
            old_name='session',
            new_name='error_location',
        ),
    ]
