# Generated by Django 3.2.13 on 2022-05-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_rename_session_errorlist_error_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlist',
            old_name='error_location',
            new_name='session',
        ),
    ]
