# Generated by Django 3.2.13 on 2022-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_rename_error_location_errorlist_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=150)),
                ('scu', models.IntegerField()),
                ('date_modified', models.IntegerField()),
            ],
        ),
    ]
