# Generated by Django 3.2.13 on 2022-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_shiplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiplist',
            old_name='scu',
            new_name='units',
        ),
        migrations.AddField(
            model_name='shiplist',
            name='implemented',
            field=models.IntegerField(default=0),
        ),
    ]
