# Generated by Django 3.2.13 on 2022-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_auto_20220602_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityprice',
            name='update',
            field=models.FloatField(default=0),
        ),
    ]
