# Generated by Django 3.2.13 on 2022-06-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_commodityprice_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofit',
            name='commodity_code',
            field=models.CharField(default='Titanium', max_length=25),
        ),
    ]
